FROM openjdk:17-jdk-slim

# Make port 8080 available to the world outside this container
EXPOSE 8080

# The application's jar file
ARG JAR_FILE=target/querydsl-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} querydsl.jar

# Run the jar file
ENTRYPOINT ["java","-jar","querydsl.jar"]