spring:
  mysql:
    console:
      enabled: true
  profiles:
    active: local
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qmsls
    username: root 
    password: 1234
# h2:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password: ignore